version: "3.8"

services:
  django_app:
    build:
      context: .
    image: django_app
    container_name: "django_cont"
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    volumes:
      - ./data/sqlite:/app/backend   # persist sqlite database file
    restart: always
    networks:
      - notes-app-nw

  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_cont"
    ports:
      - "80:80"
    restart: always
    depends_on:
      - django_app
    networks:
      - notes-app-nw

networks:
  notes-app-nw:
